#!/usr/bin/env python
#
from __future__ import absolute_import

import os
import sys
from twisted.internet import protocol, reactor

sys.path.insert(0, os.path.abspath('src/python'))

from stup import config as Config
import stup.client

factory = protocol.Factory()
factory.protocol = stup.client.Socks5AdapterProtocol
reactor.listenTCP(Config.CLIENT_PORT, factory, backlog=1)

print("Client ready to go!")

reactor.run()
